//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contexto : DbContext
    {
        public Contexto()
            : base("name=Contexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaInteresse> AreaInteresse { get; set; }
        public virtual DbSet<Atividade> Atividade { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<SalaDiscussao> SalaDiscussao { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioExpectador> UsuarioExpectador { get; set; }
        public virtual DbSet<UsuarioExpositor> UsuarioExpositor { get; set; }
        public virtual DbSet<UsuarioPadrao> UsuarioPadrao { get; set; }
        public virtual DbSet<UsuarioPromotor> UsuarioPromotor { get; set; }
    }
}
