//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Atividades = new HashSet<Atividade>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public int CodUsuario { get; set; }
        public string CPFUsuarioPromotor { get; set; }
        public Nullable<int> CodAreaInteresse { get; set; }
        public Nullable<decimal> LocalizacaoLatitude { get; set; }
        public Nullable<decimal> LocalizacaoLogitude { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
    
        public virtual AreaInteresse AreaInteresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atividade> Atividades { get; set; }
        public virtual UsuarioPromotor UsuarioPromotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
