//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioExpositor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioExpositor()
        {
            this.Atividades = new HashSet<Atividade>();
        }
    
        public int CodUsuario { get; set; }
        public string CPF { get; set; }
    
        public virtual UsuarioPadrao UsuarioPadrao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atividade> Atividades { get; set; }
    }
}
