//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterageApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnderecoUsuario
    {
        public string EmailUsuario { get; set; }
        public string Rua { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public int Numero { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
