//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterageApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int CodEvento { get; set; }
        public string TipoFeedback { get; set; }
        public string FeedbackMensagem { get; set; }
        public string EmailUsuario { get; set; }
        public int Codigo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Evento Evento { get; set; }
    }
}
