//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterageApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaDiscussao
    {
        public int Codigo { get; set; }
        public int CodAtividade { get; set; }
        public Nullable<bool> Fechada { get; set; }
        public string EmailUsuarioExpectador { get; set; }
    
        public virtual Atividade Atividade { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
