//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterageApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atividade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atividade()
        {
            this.SalasDiscussoes = new HashSet<SalaDiscussao>();
            this.Participantes = new HashSet<Usuario>();
        }
    
        public int Codigo { get; set; }
        public int CodEvento { get; set; }
        public string DescricaoAtividade { get; set; }
        public System.DateTime HorarioAtividade { get; set; }
        public string Endereco { get; set; }
        public string EmailExpositor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaDiscussao> SalasDiscussoes { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual Usuario Expositor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Participantes { get; set; }
    }
}
