// <auto-generated />
namespace InterageApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DescricaoEvento_interesse_unq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DescricaoEvento_interesse_unq));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271844200_DescricaoEvento_interesse_unq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
